name: Build
defaults:
  run:
    working-directory: app
on: 
  push:
    branches:
      - main
      - dev
      - feature/**
jobs:
  buildAndTest:
    name: Build and Test
    runs-on: macos-latest
    working-directory: app/demo
    steps:
      - uses: actions/checkout@v1
      - name: Test Build macOS
        run: xcodebuild -scheme "demo (macOS)"
      - name: Test Build iOS
        run: xcodebuild -scheme "demo (iOS)"