name: Build
defaults:
  run:
    working-directory: app
on: 
  push:
    branches:
      - main
      - dev
      - feature/**
defaults:
  run:
    working-directory: app
jobs:
  buildAndTest:
    name: Build and Test
    runs-on: osx-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: echo "Placeholder"