name: Build
defaults:
  run:
    working-directory: app/demo
on: 
  push:
    branches:
      - main
      - dev
      - feature/**
jobs:
  Lint:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Action for SwiftLint (Different working directory)
        uses: norio-nomura/action-swiftlint@3.2.1
        env:
          WORKING_DIRECTORY: app/demo/Shared
  buildAndTest:
    name: Build and Test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Test Build macOS
        run: xcodebuild -scheme "demo (macOS)"
      - name: Test Build iOS
        run: xcodebuild -scheme "demo (iOS)"